[build]
  publish = "build"

# --- WASM MIME + caching ---
[[headers]]
  for = "/wasm/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# --- JS bundles for cores ---
[[headers]]
  for = "/wasm/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

# --- Emscripten .data packages ---
[[headers]]
  for = "/*.data"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# --- Default security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
